apiVersion: v1
kind: Service
metadata:
  name: registry-worker-service
  annotations:
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
  labels:
    app: registry-worker-service
spec:
  type: LoadBalancer
  selector:
    app: registry-worker
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP