// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: google/cloud/apigeeregistry/v1/apihub/extensions.proto

// (-- api-linter: core::0215::versioned-packages=disabled
//     aip.dev/not-precedent: Support protos for the apigeeregistry.v1 API. --)

package rpc

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An ApiSpecExtensionList contains a list of extensions applicable to specs
// stored in the registry
// ApiSpecExtensionList is stored as an Artifact attached to a project.
type ApiSpecExtensionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Artifact identifier. May be used in YAML representations to indicate the id
	// to be used to attach the artifact.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Artifact kind. May be used in YAML representations to identify the type of
	// this artifact.
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// A human-friendly name for the ApiSpecExtension list.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A more detailed description of the ApiSpecExtension list.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The extensions in the list
	Extensions []*ApiSpecExtensionList_ApiSpecExtension `protobuf:"bytes,5,rep,name=extensions,proto3" json:"extensions,omitempty"`
}

func (x *ApiSpecExtensionList) Reset() {
	*x = ApiSpecExtensionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiSpecExtensionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiSpecExtensionList) ProtoMessage() {}

func (x *ApiSpecExtensionList) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiSpecExtensionList.ProtoReflect.Descriptor instead.
func (*ApiSpecExtensionList) Descriptor() ([]byte, []int) {
	return file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *ApiSpecExtensionList) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiSpecExtensionList) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ApiSpecExtensionList) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ApiSpecExtensionList) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApiSpecExtensionList) GetExtensions() []*ApiSpecExtensionList_ApiSpecExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Represents a single Extension for an ApiSpec
type ApiSpecExtensionList_ApiSpecExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the Extension
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A human-friendly name for the extension
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// A more detailed description of the extension
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// A filter expression which evaluates if the extension applies to a spec
	// e.g. mime_type.contains('openapi')
	Filter string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	// A uri pattern used to generate the target url
	UriPattern string `protobuf:"bytes,5,opt,name=uri_pattern,json=uriPattern,proto3" json:"uri_pattern,omitempty"`
}

func (x *ApiSpecExtensionList_ApiSpecExtension) Reset() {
	*x = ApiSpecExtensionList_ApiSpecExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiSpecExtensionList_ApiSpecExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiSpecExtensionList_ApiSpecExtension) ProtoMessage() {}

func (x *ApiSpecExtensionList_ApiSpecExtension) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiSpecExtensionList_ApiSpecExtension.ProtoReflect.Descriptor instead.
func (*ApiSpecExtensionList_ApiSpecExtension) Descriptor() ([]byte, []int) {
	return file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ApiSpecExtensionList_ApiSpecExtension) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiSpecExtensionList_ApiSpecExtension) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ApiSpecExtensionList_ApiSpecExtension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ApiSpecExtensionList_ApiSpecExtension) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ApiSpecExtensionList_ApiSpecExtension) GetUriPattern() string {
	if x != nil {
		return x.UriPattern
	}
	return ""
}

var File_google_cloud_apigeeregistry_v1_apihub_extensions_proto protoreflect.FileDescriptor

var file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDesc = []byte{
	0x0a, 0x36, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x61,
	0x70, 0x69, 0x67, 0x65, 0x65, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x70, 0x69, 0x68, 0x75, 0x62, 0x2f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x65, 0x65, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x68, 0x75, 0x62, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9f, 0x03, 0x0a, 0x14, 0x41, 0x70, 0x69, 0x53, 0x70, 0x65, 0x63, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x6c, 0x0a, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x65, 0x65, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x68, 0x75, 0x62, 0x2e, 0x41,
	0x70, 0x69, 0x53, 0x70, 0x65, 0x63, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x73, 0x74, 0x2e, 0x41, 0x70, 0x69, 0x53, 0x70, 0x65, 0x63, 0x45, 0x78, 0x74, 0x65, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0xaf, 0x01, 0x0a, 0x10, 0x41, 0x70, 0x69, 0x53, 0x70, 0x65, 0x63, 0x45, 0x78, 0x74, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0b,
	0x75, 0x72, 0x69, 0x5f, 0x70, 0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x0a, 0x75, 0x72, 0x69, 0x50, 0x61, 0x74, 0x74, 0x65,
	0x72, 0x6e, 0x42, 0x62, 0x0a, 0x29, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x61, 0x70, 0x69, 0x67, 0x65, 0x65, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x68, 0x75, 0x62, 0x42,
	0x0f, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x70, 0x69, 0x67, 0x65, 0x65, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x72,
	0x70, 0x63, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescOnce sync.Once
	file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescData = file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDesc
)

func file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescGZIP() []byte {
	file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescOnce.Do(func() {
		file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescData)
	})
	return file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDescData
}

var file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_goTypes = []interface{}{
	(*ApiSpecExtensionList)(nil),                  // 0: google.cloud.apigeeregistry.v1.apihub.ApiSpecExtensionList
	(*ApiSpecExtensionList_ApiSpecExtension)(nil), // 1: google.cloud.apigeeregistry.v1.apihub.ApiSpecExtensionList.ApiSpecExtension
}
var file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_depIdxs = []int32{
	1, // 0: google.cloud.apigeeregistry.v1.apihub.ApiSpecExtensionList.extensions:type_name -> google.cloud.apigeeregistry.v1.apihub.ApiSpecExtensionList.ApiSpecExtension
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_init() }
func file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_init() {
	if File_google_cloud_apigeeregistry_v1_apihub_extensions_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiSpecExtensionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiSpecExtensionList_ApiSpecExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_goTypes,
		DependencyIndexes: file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_depIdxs,
		MessageInfos:      file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_msgTypes,
	}.Build()
	File_google_cloud_apigeeregistry_v1_apihub_extensions_proto = out.File
	file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_rawDesc = nil
	file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_goTypes = nil
	file_google_cloud_apigeeregistry_v1_apihub_extensions_proto_depIdxs = nil
}
